### PR TITLE
Update Address, Map and not mentioning Zug office anymore

### PR DESCRIPTION
**Pull request by huerlisi**
We:
- moved to Sihlquai
- do not have a branch office in Zug anymore

### CODE REVIEW

**Comment by huerlisi** [comment]
Ready for review.

**Comment by toupeira** [comment]
:+1: Sorry should have checked first ;-)

**Comment by toupeira** [comment]
I'll deploy as well...

**Comment by huerlisi** [comment]
Cool, thanks!

**Pull request merged**
